- import_tasks: packages.yaml
  tags: packages

- import_tasks: network.yaml
  tags: network

- name: Copy over /etc/motd file
  copy:
    src: files/etc/motd
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: reboot (as needed)
  reboot:
    reboot_timeout: 3600
  when: cmdline or timezone or hostname or gpu_mem is changed
